Amalgamation systems: Fix definitions and simplify proofs
AliaumeL/word-ordering-wqo pull request #8
Opened 2024-10-25 15:30 UTC by strangeglyph

There were some inconsistencies in the definition of amalgamation systems which I have fixed. I also changed runs to use $\rho$, $\sigma$ and $\tau$ as names, consistent with [ASSZ] and because I think it helps readability if they have non-latin letters.

The proof that infix-wqo languages of amalgamation systems are bounded was incorrect due to lack of separator letters, but while I was at it, I think I also managed to nicely simplify it. I also simplified the decidability proof. Please have a look and see if it makes sense to you.

That infix closures of chains are regular isn't immediately obvious to me, would it make sense to add half a sentence adding an explanation?

Finally, there was a note expressing confusion about the use of "fresh" letters and different alphabets between amalgamation systems. This is not a problem, and a common definition. Consider, for example, the class of regular languages: Obviously each regular language may (but need not) have its own alphabet distinct from other languages. This also motivates "fresh" letters: Since a transduction is a mapping between languages/systems, they may differ in their alphabet.

2024-10-25 16:22 UTC, AliaumeL requested changes
Thanks for the beautiful rewrite ⭐. I did not realize the *astronomical* number of typos...
Everything is looking good except for one point: I believe the new proof of Lemma 23 is wrong at a "stringology level". I do not know how to fix it. (but I may be wrong myself too).

2024-10-25 16:22 UTC, AliaumeL commented on src/amalgam.tex
> +authors, this conjecture remained open so far. With \cref{dwclosed-infixes-wqo:lem} we are able to show it false.
Unfortunately, the complement of the set of infixes of the Thue-Morse word is not downwards closed for infixes (or at least, I don’t know how to prove it). In fact, it is not even well-quasi-ordered: the set of all words can be reflected into $L_+ + L_-$ the sets of infixes of the Thue-Mors word, and the set of non-infixes. Because $L_+$ is well-quasi-ordered, but the set of all words is not, we conclude. 

Maybe we should just drop this remark altogether.

2024-10-25 16:22 UTC, AliaumeL commented on src/amalgam.tex
> +            Specifically, for $i$ we may fix $G_{h}{i} = \GapWord{f}{j} \GapWord{g}{j}$.
Should it be `\GapWord{h}{i}`?

2024-10-25 16:22 UTC, AliaumeL commented on src/amalgam.tex
> +	The \emph{yield} of a run is obtained by projecting away the separator symbol \cansep~from the canonical decomposition, i.e. $\intro*s\yieldrun(\rho) = \project_\Sigma( \canrun[\rho])$. The language
I believe the `*s` is a typo.

2024-10-25 16:22 UTC, AliaumeL commented on src/amalgam.tex
> +	In either case, we may conclude that either $u \infleq v$ or $v \infleq u$.
Can you formally state this last line of reasoning? It feels off.

What about $u = aba$ and $v = bab$? Then $u^m v = (ab)^m abab = (ab)^{m+2}$ is included in $PInf(ab)$ but they clearly are not related for the infix relation. I may be missing something though.

2024-10-25 16:22 UTC, AliaumeL commented on src/amalgam.tex
> +    Adapting the proof of language boundedness from $\cite[Section 4.2]{ASZZ24}$, we may conclude that $\GapLanguage{\rho}{i} \subseteq \InfPeriodChain{w}$ for some $w \in \GapLanguage{\rho}{i}$.
No math delimiters are needed around citations.

2024-10-25 16:22 UTC, AliaumeL commented on src/amalgam.tex
> +    \todo[inline]{maybe elaborate on this point}
Yes completely correct, I use the particular shape of the chains: infixes of the powers of a fixed word. This means the theorem should be restated to expose this fact. 

Here would be my proof scheme:

Assume that $L$ is downwards closed and included in a finite union of sets of the form $P(x) u P(y)$ for $x,u,y$ possibly empty finite words, and where $P(u)$ is defined as the collection of all infixes of powers of $u$.

Without loss of generality, every element of this union is "really used", i.e., there are $x^n u y^n \in L$ for all $n \geq 0$ (Because of the downwards closure, we can assume it is the same $n$ and that cuts are properly made). Indeed, if only finitely many are present, we just increase the size of the union, and replace $x$ or $y$ with the empty word.

So, let us write the regular expression $x^* u y^*$, note that it is included in $L$ by our previous remark. And the converse inclusion holds almost by definition.

2024-10-26 10:11 UTC, strangeglyph commented on src/amalgam.tex
> +authors, this conjecture remained open so far. With \cref{dwclosed-infixes-wqo:lem} we are able to show it false.
Ah yeah, I misunderstood what was written there before then. I think we could just remove it, yes

2024-10-26 10:12 UTC, strangeglyph commented on src/amalgam.tex
> +            Specifically, for $i$ we may fix $G_{h}{i} = \GapWord{f}{j} \GapWord{g}{j}$.
It should be
 
> Specifically, for $i$ we may fix $G_{h}{i} = \GapWord{f}{i} \GapWord{g}{i}$

Thanks for catching that

2024-10-26 10:33 UTC, strangeglyph commented on src/amalgam.tex
> +	In either case, we may conclude that either $u \infleq v$ or $v \infleq u$.
$u^m$ would be $abaabaaba\ldots$, not $ababab\ldots$. My reasoning is as such: Let $u^mv$ and $u^nv$ in $PInf(w)$, for $m < n$. Write $n = m+k$. WLOG assume $|u^m|, |u^n|$ is a multiple of $|w|$. We may (for sufficiently large $m$) assume that there are $x \in Suff(w), y \in Pref(w)$ such that $u^m, u^n, u^k \in xw^*y$, ergo $yx = w$. Therefore write $u^m = (xy)^l$. As $u^mv \in PInf(w)$, we may assume $v$ is in prefix of $Pref((xy)^*)$. Hence either $v$ is a prefix of $u$ or vice versa.

2024-10-28 08:42 UTC, AliaumeL commented on src/amalgam.tex
> +	In either case, we may conclude that either $u \infleq v$ or $v \infleq u$.
Oh, my bad! Well, this is a very nice improvement!!

2024-10-29 08:48 UTC, merged

2024-10-29 10:01 UTC, strangeglyph commented
Wait hold up, I hadn't fixed the typos yet!

2024-11-12 08:36 UTC, AliaumeL commented
Do you want to update on your side or should I do it on the main repo?

2024-11-13 16:28 UTC, strangeglyph commented
Yeah I'm gonna take care of it